baseURL = 'https://NachoV8.github.io/hugo2/'
languageCode = 'en-us'
title = 'My First Hugo Site'
theme ='relearn'

[params]
  themeVariant = [ "zen-dark", "relearn-dark", "blue" ]


[markup]
  [markup.highlight]
    # line numbers in a table layout will shift if code is wrapping, so better
    # use inline; besides that visually both layouts have the same look and behavior
    lineNumbersInTable = false

    # if `guessSyntax = true`, there will be no unstyled code even if no language
    # was given BUT Mermaid and Math codefences will not work anymore! So this is a
    # mandatory setting for your site if you want to use Mermaid or Math codefences
    guessSyntax = false

    # the shipped variants come with their own modified chroma syntax highlightning
    # style which is imported in theme-relearn-light.css, theme-relearn-dark.css, etc.;
    # if you want to use a predefined style instead:
    # - remove `noClasses` or set `noClasses = true`
    # - set `style` to a predefined style name
    noClasses = false
    # style = "tango"

[[menu.shortcuts]]
name= "<i class='fab fa-php'></i> php"
url = "https://php.net"
weight = 10

[[menu.shortcuts]]
name= "<i class='fab fa-github'></i> Github"
url = "https://github.com"
weight = 12

[Languages]
    [Languages.es]
        title = "Español"
        weight = 1
        languageName = "Español"
        ContentDir="content/es"
    [Languages.en]
        title = "Ingles"
        weight = 2
        languageName = "English"
        ContentDir="content/en"
   [Languages.fr]
        title = "Frances  "
        weight = 3
        languageName = "Français"
        ContentDir="content/fr"

defaultContentLanguage = 'es'



